server:
  port: 8080
  tomcat:
    access-log-enabled: true
  servlet:
    context-path: /api

spring:
  application:
    name: perfect-number-api

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG