apiVersion: v1
kind: Pod
metadata:
  name: perfect-number-api
  labels:
    app: perfect-number-api
spec:
  containers:
  - name: perfect-number-api
    image: njaneto/perfect-number-api:v1
    ports:
    - containerPort: 8080